---
- name: run yolo app  
  hosts: all
  become: yes
  gather_facts: no
  roles: 
    - ansible-roles
  vars:
    docker_url: https://download.docker.com/linux/ubuntu/gpg

  tasks:
      
   - name: start docker service
     service:
        name: docker
        state: started
        enabled: yes
     become: true
     tags:
       - start

   - name: copy docker-compose.yml
     copy: 
       src: docker-compose.yml
       dest: /home/vagrant
     become: true   

   - name: run docker compose
     command: docker compose up -d
     tags:
       - deploy
  