---
- name: run yolo app  
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install docker
      apt:
        name:
          - docker-ce
          - containerd.io

    - name: add userpermissions
      shell: "usermod -aG docker vagrant"

    - name: install pip3
      apt:  
        name: python3-pip
        state: present

    - name: install python sdk
      become_user: vagrant
      pip:
        name:
          - docker
          - docker-compose
